name: spic_app
description: SPIC VPN client based on TrustTunnel
publish_to: 'none'

version: 1.0.22+23

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  trusttunnel:
    path: ../../TrustTunnelFlutterClient
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SpicFont
      fonts:
        - asset: assets/fonts/roboto-regular.ttf
          weight: 300
